= PERPET MATCH REST API Guide
백승열;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head

[[introduction]]
== 소개

퍼펫 매치(Perpet Match) API 서버입니다.


[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `401 unAuthorized`
| 토큰을 가지지 않고 API를 요청하는 경우.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우.

| `404 Not Found`
| 요청한 리소스가 없음.
|===


== 공통 응답

|===
| 환경 | Domain

| 개발서버
| `http://perpetapi.com:8080/`

| 운영서버
|
|===


|===
|코드|코드명|필수값

|success|성공 유무|true
|message|결과 메세지|true
|data|데이터|false
|===

== 공통 헤더
|===
|헤더|토큰|필수값
|Authorization|Bearer 토큰| true ( 회원가입 제외 )
|===


[[members]]
== 회원

회원 가입을 해야 토큰을 발급받을 수 있다. 토큰이 없는 경우 API를 사용할 수 없다.

[[members-signup]]
=== 회원가입

`POST` 요청을 사용하여 퍼펫 매치 서비스에 회원가입 할 수 있다.

operation::sign-up[snippets='request-fields,response-fields,http-request,http-response']

[[members-signin]]
=== 로그인

`POST` 요청을 사용하여 퍼펫 매치 서비스에 로그인 할 수 있다.

operation::sign-in[snippets='request-fields,response-fields,http-request,http-response']

[[profile]]
== 프로필

프로필 관련


[[profile-password]]
=== 패스워드 변경

`PUT` 요청을 사용하여 해당 유저의 비밀번호를 변경할 수 있다.

operation::update-password[snippets='request-fields,response-fields,http-request,http-response']

[[my-profile]]
=== 자신의 프로필 조회

'GET' 요청을 사용하여 자신의 프로필을 조회할 수 있다.

operation::my-profile[snippets='response-fields,http-request,http-response']


[[profile-show]]
=== 프로필 단일 조회

'GET/{id}' 요청을 사용하여 해당 유저의 프로필을 조회할 수 있다.

operation::show-profile[snippets='path-parameters,response-fields,http-request,http-response']

[[profile-create]]
=== 기본 프로필 등록

'POST' 요청을 사용하여 해당 유저의 기본 프로필을 등록할 수 있다.

operation::create-profile[snippets='request-fields,response-fields,http-request,http-response']

[[my-credit]]
=== 자신의 크레딧(껌) 조회

'GET /api/profiles/credit' 요청을 사용하여 자신의 껌(크레딧)을 조회할 수 있다.

operation::get-credit[snippets='response-fields,http-request,http-response']


[[petTitle]]
=== 관심 품종

[[petTitle-get]]
==== 관심 품종 조회

'GET' 요청을 사용하여 해당 유저의 관심 품종을 조회할 수 있다.

operation::show-petTitle[snippets='response-fields,http-request,http-response']

[[petTitle-create]]
==== 관심 품종 등록

'POST' 요청을 사용하여 해당 유저의 관심 품종을 등록할 수 있다.

operation::update-petTitle[snippets='request-fields,response-fields,http-request,http-response']

[[petTitle-remove]]
==== 관심 품종 제거

'DELETE' 요청을 사용하여 해당 유저의 관심 품종을 제거할 수 있다.

operation::remove-petTitle[snippets='request-fields,response-fields,http-request,http-response']

[[petAge]]
=== 관심 나이

[[petAge-get]]
==== 관심 나이 조회

'GET' 요청을 사용하여 해당 유저의 관심 나이를 조회할 수 있다.

operation::show-petAge[snippets='response-fields,http-request,http-response']

[[petAge-create]]
==== 관심 나이 등록

'POST' 요청을 사용하여 해당 유저의 관심 나이를 등록할 수 있다.

operation::update-petAge[snippets='request-fields,response-fields,http-request,http-response']

[[petAge-remove]]
==== 관심 나이 제거

'DELETE' 요청을 사용하여 해당 유저의 관심 나이를 제거할 수 있다.

operation::remove-petAge[snippets='request-fields,response-fields,http-request,http-response']

[[Zone]]
=== 관심 지역

[[petZone-get]]
==== 관심 지역 조회

'GET' 요청을 사용하여 해당 유저의 관심 지역을 조회할 수 있다.

operation::show-zone[snippets='response-fields,http-request,http-response']

[[petZone-create]]
==== 관심 지역 등록

'POST' 요청을 사용하여 해당 유저의 관심 지역을 등록할 수 있다.

operation::update-petZone[snippets='request-fields,response-fields,http-request,http-response']

[[petZone-remove]]
==== 관심 지역 제거

'DELETE' 요청을 사용하여 해당 유저의 관심 지역을 제거할 수 있다.

operation::remove-petZone[snippets='request-fields,response-fields,http-request,http-response']


[[board]]
== 파양하기 게시판

파양하기 관련

[[board-create]]
=== 파양하기 게시글 등록

'POST' 요청을 사용하여 파양하기 게시글을 만들 수 있다.

operation::create-board[snippets='request-fields,response-fields,http-request,http-response']


[[show-board]]
=== 파양하기 게시글 단일 조회

'GET/{id}' 요청을 사용하여 게시글을 조회할 수 있다.

operation::show-board[snippets='path-parameters,response-fields,http-request,http-response']

[[get-boards]]
=== 파양하기 게시글 다건 조회

'GET' 요청을 사용하여 게시글을 다건 조회할 수 있다.

operation::get-boards[snippets='response-fields,http-request,http-response']

[[accept-credit]]
=== 파양하기 입양 유저 수락

'POST /api/boards/{id}/accept' 요청을 사용하여 수락할 유저를 선택할 수 있다.

operation::accept-credit[snippets='path-parameters,request-fields,response-fields,http-request,http-response']


[[Adoption]]
== 입양하기

[[adopt-apply]]
=== 입양하기 신청

'POST' 요청을 사용하여 입양 게시글에 신청할 수 있다.  최초 누를 시 신청이 되고 신청이 된 상태에서 다시 한번 누르면 신청이 취소된다.

operation::adopt-apply[snippets='path-parameters,response-fields,http-request,http-response']

[[applied_me]]
=== 신청 여부 확인하기

'GET /api/boards/{id}/applied_me' 요청을 사용하여 현재 신청한 유저인지 success = true,false 를 알 수 있다.

operation::applied_me[snippets='path-parameters,response-fields,http-request,http-response']




[[apply-list]]
=== 신청 리스트 보기

'GET' 요청을 사용하여 해당 글의 주인은 입양 신청 리스트를 가져올 수 있다.


operation::apply-list[snippets='path-parameters,response-fields,http-request,http-response']

==== users 데이터
users[0], users[1] 각각의 데이터는 다음과 같다.

|====
|코드|코드명|필수값

|id|NUMBER|true
|nickname|STRING|true
|profileImage|STRING|true
|description|STRING|true
|====

[[apply-like]]
=== 즐겨찾기 등록하기

'POST' 요청을 사용하여 해당 글의 즐겨찾기를 등록할 수 있다. 최초 누를 시 즐겨찾기가 추가 되며 다시 한번 누를 시 제거 된다.

operation::like-apply[snippets='path-parameters,response-fields,http-request,http-response']

[[search-board]]
=== 입양하기 키워드 검색


'GET /api/boards/search?keyword=' 요청을 사용하여 keyword 조건에 맞는 게시글을 불러올 수 있다.
keyword의 조건은 제목, 지역, 나이 범위, 픔종 이다.


operation::search-board[snippets='response-fields,http-request,http-response']


[[searchProfile-board]]
=== 입양하기 프로필 기반 검색


'GET /api/boards/profile/search' 요청을 사용하여 조건에 맞는 게시글을 불러올 수 있다.

operation::searchProfile-board[snippets='response-fields,http-request,http-response']


이때 'GET' 요청에 실어 보내야 할 객체는 다음과 같다.

==== 입양하기 프로필 객체
|====
|코드|코드명|필수값
|zones|ARRAY|false
|petTitles|ARRAY|false
|petAges|STRING|false
|wantCheckUp|Boolean|false
|wantLineAge|Boolean|false
|wantNeutered|Boolean|false
|credit|Number|false
|====



[[Shopping]]
== 쇼핑하기

[[list-feed]]
=== 사료 아이템 다건 조회

'GET /api/shop/feeds' 요청을 사용하여 사료 데이터 리스트를 가져올 수 있다.

operation::list-feeds[snippets='response-fields,http-request,http-response']

[[list-snack]]
=== 간식 아이템 다건 조회

'GET /api/shop/snacks' 요청을 사용하여 간식 데이터 리스트를 가져올 수 있다.

operation::list-snacks[snippets='response-fields,http-request,http-response']

[[list-goods]]
=== 용품 아이템 다건 조회

'GET /api/shop/goods' 요청을 사용하여 용품 데이터 리스트를 가져올 수 있다.

operation::list-goods[snippets='response-fields,http-request,http-response']

[[item-best]]
=== 베스트 아이템 조회

'GET /api/shop/items/best' 요청을 사용하여 베스트 아이템 리스트를 가져올 수 있다.

operation::item-best[snippets='response-fields,http-request,http-response']

[[item-new]]
=== 신규 아이템 조회

'GET /api/shop/items/new' 요청을 사용하여 신규 아이템 리스트를 가져올 수 있다.

operation::item-new[snippets='response-fields,http-request,http-response']




[[get-item]]
=== 쇼핑 아이템 단일 조회

'GET /api/shop/details/{id}' 요청을 사용하여 단일 아이템을 조회할 수 있다.

operation::get-item[snippets='path-parameters,response-fields,http-request,http-response']

[[add-bag]]
=== 장바구니 추가


'POST /api/order/bags/{id}' 요청을 사용하여 장바구니에 아이템을 추가할 수 있다.

operation::add-bag[snippets='path-parameters,request-fields,response-fields,http-request,http-response']

[[remove-bag]]
=== 장바구니 삭제

'DELETE /api/order/bags/details/{id}' 요청을 사용하여 해당 장바구니 아이템을 삭제할 수 있다.

operation::remove-bag[snippets='path-parameters,response-fields,http-request,http-response']

[[bag-list]]
=== 유저의 장바구니 리스트 조회

'GET /api/order/bags' 요청을 사용하여 해당 유저의 장바구니 리스트를 조회할 수 있다.

operation::bag-list[snippets='response-fields,http-request,http-response']

[[shop-payment]]
=== 장바구니 결제하기

'POST /api/order/bags/pay' 요청을 사용하여 장바구니에 있는 아이템들을 결제할 수 있다.

operation::shop-payment[snippets='request-fields,response-fields,http-request,http-response']

//[[resources-events-get]]
//=== 이벤트 조회
//
//`Get` 요청을 사용해서 기존 이벤트 하나를 조회할 수 있다.
//
//operation::sign-up[snippets='request-fields,curl-request,http-response']
//
//[[resources-events-update]]
//=== 이벤트 수정
//
//`PUT` 요청을 사용해서 기존 이벤트를 수정할 수 있다.
//
//operation::sign-up[snippets='request-fields,curl-request,http-response']